version: "3.7"
services:
  shinobi:
    image: shinobisystems/shinobi:latest-ubuntu
    labels:
      - "traefik.http.routers.whoami.rule=Host(`shinobi.site.workhub99.org`)"
      - "traefik.http.services.shinobi.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_default"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myhttpchallenge"
    environment:
      - TZ=America/New_York
      - APP_BRANCH=dev
      - DEBUG=1
      - PUID=2022
      - PGID=2022
    networks:
      outside-world:
    volumes:
      - "/dev/shm/shinobiStreams:/dev/shm/streams:Z"
      - "/docker/nfs_mount/shinobi/shinobiConfig:/config:Z"
      - "/docker/nfs_mount/shinobi/shinobiCustomAutoLoad:/customAutoLoad:Z"
      - "/docker/nfs_mount/shinobi/shinobiDatabase:/var/lib/mysql:Z"
      - "/docker/nfs_mount/shinobi/shinobiVideos:/opt/shinobi/videos:Z"
      - "/docker/nfs_mount/shinobi/conf.json:/opt/shinobi/conf.json"
      - "/docker/nfs_mount/shinobi/super.json:/opt/shinobi/super.json"

networks:
  outside-world:
    external:
      name: traefik_outside-world
